// Generated by tool/update_version.dart. Do not edit.
//
// The version of this package, which `pubspec.yaml` holds and nothing can
// read from there at run time.

/// The version of this package, as its pubspec gives it.
const String packageVersion = '0.1.0';
