import 'dart:io';

/// Writes `lib/src/version.dart` from the version in `pubspec.yaml`.
///
/// The version has to exist as a constant, because `pubspec.yaml` is not
/// around at run time: a published package is source on disk, or compiled
/// into something with no files next to it at all. Rather than keep the two
/// in step by hand, this writes one from the other:
///
/// ```
/// dart run tool/update_version.dart
/// ```
///
/// `test/version_test.dart` fails while they disagree, so a version bumped
/// without running this does not get past the tests.
///
/// Written here rather than taken from a builder package because it is this
/// much code, and build_runner would be the only thing standing behind a
/// package whose argument is that nothing does.
void main() {
  final pubspec = File('pubspec.yaml');
  if (!pubspec.existsSync()) {
    stderr.writeln('Run this from the root of the package.');
    exitCode = 1;
    return;
  }

  final version = readVersion(pubspec.readAsStringSync());
  if (version == null) {
    stderr.writeln('pubspec.yaml does not give a version.');
    exitCode = 1;
    return;
  }

  final out = File('lib/src/version.dart');
  final was = out.existsSync() ? out.readAsStringSync() : '';
  final now = source(version);
  if (was == now) {
    stdout.writeln('lib/src/version.dart is already $version.');
    return;
  }
  out.writeAsStringSync(now);
  stdout.writeln('Wrote lib/src/version.dart at $version.');
}

/// The `version:` a pubspec gives, or null if it gives none.
///
/// A line at the top level of the document, which is all pub allows it to be
/// and all this has to understand.
String? readVersion(String pubspec) => RegExp(
      r'''^version:\s*["']?([^"'\s#]+)["']?''',
      multiLine: true,
    ).firstMatch(pubspec)?.group(1);

/// The file to write for [version].
String source(String version) => '''
// Generated by tool/update_version.dart. Do not edit.
//
// The version of this package, which `pubspec.yaml` holds and nothing can
// read from there at run time.

/// The version of this package, as its pubspec gives it.
const String packageVersion = '$version';
''';
